# Importing libraries

In [1]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

# Simple Dataset

In [5]:
class toy_set(Dataset):
    
    # Constructor
    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform
    
    # Getter
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    # Get Length
    def __len__(self):
        return self.len

In [6]:
d1 = toy_set()
d1

In [7]:
d1[0]

(tensor([2., 2.]), tensor([1.]))

In [8]:
len(d1)

100

In [9]:
for i in range(3):
    x, y = d1[i]
    print(f"{i}: x:{x}, y:{y}")

0: x:tensor([2., 2.]), y:tensor([1.])
1: x:tensor([2., 2.]), y:tensor([1.])
2: x:tensor([2., 2.]), y:tensor([1.])


In [10]:
for x, y in d1:
    print(x, y)
    break

tensor([2., 2.]) tensor([1.])


# Transforms

A calss for transforming the data

In [11]:
class add_mult(object):
    
    # Constructor
    def __init__(self, addx = 1, muly = 1):
        self.addx = addx
        self.muly = muly
    
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        return x, y

In [12]:
t1 = add_mult()
d1 = toy_set()

In [13]:
for i in range(10):
    x, y = d1[i]
    print(f"x:{x}, y:{y}")
    x_, y_ = t1(d1[i])
    print(f"x_:{x_}, y_:{y_}")

x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])
x:tensor([2., 2.]), y:tensor([1.])
x_:tensor([3., 3.]), y_:tensor([1.])


In [14]:
d2 = toy_set(transform = t1)
for x, y in d2:
    print(x, y)
    break

tensor([3., 3.]) tensor([1.])


# Compose multiple transform

In [18]:
from torchvision import transforms

In [19]:
class mult(object):
    
    def __init__(self, mult = 100):
        self.mult = mult
    
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        return x, y

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.3.1_trasform.png" width="500" alt="Compose PyTorch">

In [20]:
data_transform = transforms.Compose([add_mult(), mult()])
data_transform

Compose(
)

In [21]:
data_transform(d1[0])

(tensor([300., 300.]), tensor([100.]))

In [24]:
x, y = d1[0]
print(x, y)
x_, y_ = data_transform(d1[0])
print(x_, y_)

tensor([2., 2.]) tensor([1.])
tensor([300., 300.]) tensor([100.])
