# Importing libraries

In [1]:
from torch import nn
import torch
torch.manual_seed(1)

# Prediction

In [2]:
w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

<code>torch.mm</code> is Matrix Multiplication

In [3]:
def forward(x):
    yhat = torch.mm(x,w) + b
    return yhat

In [4]:
x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print(yhat)

tensor([[9.]], grad_fn=<AddBackward0>)


In [5]:
X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])
yhat = forward(X)
print(yhat)

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


# Class Linear

In [6]:
model = nn.Linear(2,1)

In [7]:
model(x)

tensor([[-0.3969]], grad_fn=<AddmmBackward>)

In [8]:
model(X)

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward>)

In [9]:
model.state_dict()

OrderedDict([('weight', tensor([[ 0.3643, -0.3121]])),
             ('bias', tensor([-0.1371]))])

# Custom Module

In [10]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        return model(x)

In [11]:
model2 = LR(2,1)

In [12]:
model2(x)

tensor([[-0.3969]], grad_fn=<AddmmBackward>)

In [16]:
model2(X)

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward>)

In [15]:
model2.state_dict()

OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])),
             ('linear.bias', tensor([0.4241]))])