# Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

# Types and Shape

In [2]:
l1 = [[10, 11, 12],
     [20, 21, 22],
     [30, 31, 32]]
t1 = torch.tensor(l1)
t1

tensor([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])

## .ndimension() .shape .size() .numel()

In [3]:
t1.ndimension()

2

In [4]:
t1.shape

torch.Size([3, 3])

In [6]:
t1.size()

torch.Size([3, 3])

In [7]:
t1.numel()

9

## torch.from_numpy()

In [8]:
df = pd.DataFrame({'a': [10, 11, 12], 'b': [20, 21, 22]})
print(df.values)
print(df.values.dtype)

[[10 20]
 [11 21]
 [12 22]]
int64


In [9]:
t2 = torch.from_numpy(df.values)
print(t2)
print(t2.dtype)

tensor([[10, 20],
        [11, 21],
        [12, 22]])
torch.int64


# Indexing and Slicing

In [10]:
t1[1, 2]

tensor(22)

In [11]:
t1[1][2]

tensor(22)

In [12]:
t1[1,:]

tensor([20, 21, 22])

In [13]:
t1[:,2]

tensor([12, 22, 32])

In [14]:
t1[0:2,1]

tensor([11, 21])

In [15]:
t1[0:3,1]

tensor([11, 21, 31])

In [16]:
t1[0:3,1:3]

tensor([[11, 12],
        [21, 22],
        [31, 32]])

# Operations

In [18]:
t1 = torch.tensor([[1, 2], [2, 1]])
t2 = torch.tensor([[0, 1], [1, 0]])
t1 + t2

tensor([[1, 3],
        [3, 1]])

In [22]:
t1 - t2

tensor([[1, 1],
        [1, 1]])

In [19]:
t1 * t2

tensor([[0, 2],
        [2, 0]])

In [20]:
t1 * 2

tensor([[2, 4],
        [4, 2]])

## Matrix Multiplication (mm)

In [21]:
torch.mm(t1, t2)

tensor([[2, 1],
        [1, 2]])